#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## Script to manage brightness on Archcraft.

# Icons
icons='/usr/share/archcraft/icons/dunst'

# Get brightness
get_backlight(){
    echo $(printf "%.0f" `light -G`)
}

# Get icons
get_icon(){
	current="$(get_backlight)"
    if [[ $current -ge 80 ]]; then
        icon="$icons/brightness-100.png"
    elif [[ $current -ge 60 ]]; then
        icon="$icons/brightness-80.png"
    elif [[ $current -ge 40 ]]; then
        icon="$icons/brightness-60.png"
    elif [[ $current -ge 20 ]]; then
        icon="$icons/brightness-40.png"
    else
        icon="$icons/brightness-20.png"
    fi
}

# Notify 
notify_bl() {
	get_icon && 
    dunstify -u low -h string:x-dunst-stack-tag:obbacklight -i "$icon" "Brightness : $(get_backlight)%"
}

# Increase brightness
inc_backlight() {
	light -A 5 && notify_bl
}

# Decrease brightness
dec_backlight() {
    light -U 5 && notify_bl
}

# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
fi
