#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## ~~ Edit 2023 Inqognitoo <alexinq6@gmail.com> 
##
## Launch bspwm bar.

# force tray icons to use tela-dark
XDG_CURRENT_DESKTOP=XFCE

# bspwm directory
DIR="$HOME/.config/bspwm"

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar ~
bash "$DIR/polybar/launch.sh"
