#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
DIR="$HOME/.config/bspwm/dunst"

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

if [[ "$1" == "--transparent" ]]; then
    dunst -config "$DIR"/dunstrc-transparent &
else
    dunst -config "$DIR"/dunstrc &
fi
