#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## ~~~ Edit 2023 Inqognitoo <alexinq6@gmail.com>
##
## launch alacritty with bspwm config

# bspwm directory
DIR="$HOME/.config/bspwm"
CONFIG="$DIR/alacritty/alacritty.yml"

alacritty --config-file "$CONFIG" "$@"
